version: '3'

services:
  ddns:
    container_name: ddns
    image: joshava/cloudflare-ddns
    hostname: $HOSTNAME
    volumes:
      - ./ddns/config.yaml:/app/config.yaml:ro
      - /etc/localtime:/etc/localtime:ro

  nginx:
    container_name: nginx
    image: nginx
    command: >
      /bin/bash -c
      "echo $USERNAME:{PLAIN}$PASSWORD > /etc/nginx/.htpasswd &&
       envsubst '$$DOMAIN' < etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
       exec nginx -g 'daemon off;'"
    hostname: $HOSTNAME
    environment:
      DOMAIN: $DOMAIN
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/nginx/logs:/var/log/nginx/logs
      - $SERVER_DIR/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./nginx/auth-basic.conf:/etc/nginx/auth-basic.conf:ro
      - ./nginx/auth-location.conf:/etc/nginx/auth-location.conf:ro
      - ./nginx/auth-request.conf:/etc/nginx/auth-request.conf:ro
      - ./nginx/proxy-pass.conf:/etc/nginx/proxy-pass.conf:ro

  oidc:
    container_name: oidc
    image: pkoenig10/oidc-rp
    command: >
      -client-id $CLIENT_ID
      -client-secret $CLIENT_SECRET
      -cookie-secret $COOKIE_SECRET
      -cookie-domain $DOMAIN
      -redirect-url https://auth.$DOMAIN
      -users-file /users.yml
    hostname: $HOSTNAME
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./oidc/users.yml:/users.yml:ro

  netdata:
    container_name: netdata
    image: netdata/netdata
    hostname: $HOSTNAME
    environment:
      PGID: $DOCKER_GID
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $SERVER_DIR/nginx/logs:/var/log/nginx:ro
      - $DATA_DIR:/data
      - ./netdata/netdata.conf:/etc/netdata/netdata.conf:ro
      - ./netdata/apps_groups.conf:/etc/netdata/apps_groups.conf:ro
      - ./netdata/fping.conf:/etc/netdata/fping.conf:ro
      - ./netdata/nginx.conf:/etc/netdata/python.d/nginx.conf:ro
      - ./netdata/web_log.conf:/etc/netdata/python.d/web_log.conf:ro

  influxdb:
    container_name: influxdb
    image: influxdb
    hostname: $HOSTNAME
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana:
    container_name: grafana
    image: grafana/grafana
    hostname: $HOSTNAME
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro

  pihole:
    container_name: pihole
    image: pihole/pihole
    hostname: pihole
    environment:
      WEBPASSWORD: $PASSWORD
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    ports:
      - $LOCAL_IP:53:53/tcp
      - $LOCAL_IP:53:53/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/pihole/pihole:/etc/pihole
      - $SERVER_DIR/pihole/dnsmasq:/etc/dnsmasq.d

  iperf:
    container_name: iperf
    image: networkstatic/iperf3
    command: >
      -s
    hostname: $HOSTNAME
    restart: unless-stopped
    ports:
      - 5201:5201
    volumes:
      - /etc/localtime:/etc/localtime:ro

  plex:
    container_name: plex
    image: plexinc/pms-docker:beta
    hostname: $HOSTNAME
    environment:
      PLEX_UID: $UID
      PLEX_GID: $GID
      ADVERTISE_IP: http://$LOCAL_IP:32400
      ALLOWED_NETWORKS: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    devices:
      - /dev/dri
    restart: unless-stopped
    ports:
      - 32400:32400
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/plex/config:/config
      - $DATA_DIR/tv:/tv
      - $DATA_DIR/movies:/movies

  tautulli:
    container_name: tautulli
    image: tautulli/tautulli
    hostname: $HOSTNAME
    environment:
      PUID: $UID
      PGID: $GID
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/tautulli/config:/config

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    hostname: $HOSTNAME
    environment: &environment-linuxserver
      PUID: $UID
      PGID: $GID
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/radarr/config:/config
      - $DATA_DIR/downloads:/downloads
      - $DATA_DIR/movies:/movies

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    hostname: $HOSTNAME
    environment: *environment-linuxserver
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/sonarr/config:/config
      - $DATA_DIR/downloads:/downloads
      - $DATA_DIR/tv:/tv

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    hostname: $HOSTNAME
    environment: *environment-linuxserver
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/jackett/config:/config

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    hostname: $HOSTNAME
    environment:
      OPENVPN_PROVIDER: $OPENVPN_PROVIDER
      OPENVPN_USERNAME: $OPENVPN_USERNAME
      OPENVPN_PASSWORD: $OPENVPN_PASSWORD
      TRANSMISSION_DOWNLOAD_DIR: /downloads/complete
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_HOME: /transmission
      TRANSMISSION_WEB_HOME: /web
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SERVER_DIR/transmission:/transmission
      - $DATA_DIR/downloads:/downloads
      - $TRANSMISSION_WEB_DIR:/web:ro

  spyfall:
    container_name: spyfall
    image: pkoenig10/spyfall
    hostname: $HOSTNAME
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    command: >
      --schedule "0 0 4 * * *"
      --cleanup
    hostname: $HOSTNAME
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
