version: '3.7'

services:
  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare
    command: >
      certonly
      --email $EMAIL
      --cert-name $DOMAIN
      --domains $DOMAIN
      --domains *.$DOMAIN
      --dns-cloudflare
      --dns-cloudflare-credentials /cloudflare.ini
      --agree-tos
      --keep-until-expiring
      --must-staple
    network_mode: host
    volumes:
      - $SERVER_DIR/letsencrypt:/etc/letsencrypt
      - ./cloudflare/cloudflare.ini:/cloudflare.ini:ro

  backup:
    container_name: backup
    image: pkoenig10/dbxcli-backup
    environment:
      NAME: $HOSTNAME
    network_mode: host
    volumes:
      - $SERVER_DIR:/files
      - $SERVER_DIR/dbxcli:/root/.config/dbxcli
      - ./backup/backup.conf:/etc/backup/backup.conf:ro
