version: '3'

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: >
      certonly
      --config /etc/letencrypt/cli.ini
      --email $EMAIL
      --cert-name $DOMAIN
      --domains $DOMAIN
      --domains *.$DOMAIN
    volumes:
      - ../certbot/cli.ini:/etc/letencrypt/cli.ini:ro
      - $SERVER_DIR/letsencrypt:/etc/letsencrypt

  backup:
    container_name: backup
    image: pkoenig10/dbxcli-backup
    environment:
      TZ: $TZ
      NAME: $HOSTNAME
    volumes:
      - $SERVER_DIR:/files
      - $SERVER_DIR/dbxcli:/root/.config/dbxcli
      - ../backup/backup.conf:/etc/backup/backup.conf
