version: '3'

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: >
      certonly
      --email $EMAIL
      --cert-name $DOMAIN
      --domains $DOMAIN
      --domains *.$DOMAIN
      --manual
      --preferred-challenges dns
      --agree-tos
      --manual-public-ip-logging-ok
      --keep-until-expiring
      --must-staple
    volumes:
      - $SERVER_DIR/letsencrypt:/etc/letsencrypt

  backup:
    container_name: backup
    image: pkoenig10/dbxcli-backup
    environment:
      NAME: $HOSTNAME
    volumes:
      - $SERVER_DIR:/files
      - $SERVER_DIR/dbxcli:/root/.config/dbxcli
      - ../backup/backup.conf:/etc/backup/backup.conf
