version: '3'

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: >
      certonly
      --config /etc/letencrypt/cli.ini
      --email $EMAIL
      --cert-name $DOMAIN
      --domains $DOMAIN
      --domains netdata.$DOMAIN
      --domains grafana.$DOMAIN
      --domains plex.$DOMAIN
      --domains tautulli.$DOMAIN
      --domains tv.$DOMAIN
      --domains movies.$DOMAIN
      --domains jackett.$DOMAIN
      --domains downloads.$DOMAIN
      --domains spyfall.$DOMAIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../certbot/cli.ini:/etc/letencrypt/cli.ini:ro
      - letsencrypt:/etc/letsencrypt

  backup:
    container_name: backup
    image: pkoenig10/dbxcli-backup
    environment:
      TZ: $TZ
      NAME: $HOSTNAME
    volumes:
      - $CONFIG_DIR:/files
      - ../backup/backup.conf:/etc/backup/backup.conf
      - dbxcli:/root/.config/dbxcli

volumes:
  letsencrypt:
    external: true
  dbxcli:
