version: '3'

services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: >
      certonly
      --config /etc/letencrypt/cli.ini
      --email $EMAIL
      --cert-name $DOMAIN
      --domains $DOMAIN
      --domains netdata.$DOMAIN
      --domains grafana.$DOMAIN
      --domains plex.$DOMAIN
      --domains plexpy.$DOMAIN
      --domains tv.$DOMAIN
      --domains movies.$DOMAIN
      --domains trackers.$DOMAIN
      --domains transmission.$DOMAIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cli.ini:/etc/letencrypt/cli.ini:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
    external: true
